const followers = [
    {
        image: "/static/avatar/040-man-11.svg",
        name: "Mr. Breast",
        profession: "Product Designer",
        following: true,
    },
    {
        image: "/static/avatar/041-woman-11.svg",
        name: "Ethan Drake",
        profession: "UI Designer",
        following: true,
    },
    {
        image: "/static/avatar/042-vampire.svg",
        name: "Selena Gomez",
        profession: "Marketing Manager",
        following: false,
    },
    {
        image: "/static/avatar/043-chef.svg",
        name: "Sally Becker",
        profession: "UI Designer",
        following: true,
    },
    {
        image: "/static/avatar/044-farmer.svg",
        name: "Dua Lipa",
        profession: "Marketing Manager",
        following: false,
    },
    {
        image: "/static/avatar/045-man-12.svg",
        name: "Joe Murry",
        profession: "Product Designer",
        following: true,
    },
    {
        image: "/static/avatar/040-man-11.svg",
        name: "Mr. Breast",
        profession: "Product Designer",
        following: true,
    },
    {
        image: "/static/avatar/041-woman-11.svg",
        name: "Ethan Drake",
        profession: "UI Designer",
        following: true,
    },
    {
        image: "/static/avatar/042-vampire.svg",
        name: "Selena Gomez",
        profession: "Marketing Manager",
        following: false,
    },
    {
        image: "/static/avatar/043-chef.svg",
        name: "Sally Becker",
        profession: "UI Designer",
        following: true,
    },
    {
        image: "/static/avatar/044-farmer.svg",
        name: "Dua Lipa",
        profession: "Marketing Manager",
        following: false,
    },
    {
        image: "/static/avatar/045-man-12.svg",
        name: "Joe Murry",
        profession: "Product Designer",
        following: true,
    },
];

const friends = [
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
    {
        name: "Selena Gomez",
        image: "/static/avatar/012-woman-2.svg",
        profession: "Marketing Manager",
        facebookUrl: "",
        twitterUrl: "",
        instagramUrl: "",
        dribbleUrl: "",
    },
];

export {
    followers,
    friends
}